// Constants shared across the connection editor/viewer surfaces. Extracted
// from ConnectionsPanel.tsx (#766) so the panel, editor, and viewer can each
// import only what they render.

// Connection kinds the create form offers. Kind is immutable after creation.
export const AVAILABLE_KINDS = ["trino", "s3", "mcp", "api", "graphql"];

// Kind badge colors for the list and viewer header.
const KIND_COLORS: Record<string, string> = {
  trino: "bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-400",
  datahub:
    "bg-purple-100 text-purple-800 dark:bg-purple-900/30 dark:text-purple-400",
  s3: "bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-400",
  mcp: "bg-emerald-100 text-emerald-800 dark:bg-emerald-900/30 dark:text-emerald-400",
  api: "bg-indigo-100 text-indigo-800 dark:bg-indigo-900/30 dark:text-indigo-400",
  graphql: "bg-pink-100 text-pink-800 dark:bg-pink-900/30 dark:text-pink-400",
};

export function kindColor(kind: string): string {
  return KIND_COLORS[kind] ?? "bg-muted text-muted-foreground";
}

// Human labels for raw config keys, keyed by kind, used by the read-only
// viewer's Configuration table.
export const CONFIG_LABELS: Record<string, Record<string, string>> = {
  trino: {
    host: "Host",
    port: "Port",
    user: "Username",
    password: "Password",
    catalog: "Default Catalog",
    schema: "Default Schema",
    ssl: "SSL / TLS",
    ssl_verify: "SSL Verify",
    read_only: "Read Only",
    default_limit: "Default Limit",
    max_limit: "Max Limit",
    timeout: "Timeout",
    connection_name: "Connection Name",
    description: "Description",
  },
  s3: {
    endpoint: "Endpoint",
    region: "Region",
    access_key_id: "Access Key ID",
    secret_access_key: "Secret Access Key",
    session_token: "Session Token",
    profile: "Profile",
    bucket_prefix: "Bucket Prefix",
    use_path_style: "Force Path Style",
    disable_ssl: "Disable SSL",
    read_only: "Read Only",
    timeout: "Timeout",
    max_get_size: "Max GET Size",
    max_put_size: "Max PUT Size",
    connection_name: "Connection Name",
  },
  mcp: {
    endpoint: "Endpoint",
    auth_mode: "Auth Mode",
    credential: "Credential",
    connect_timeout: "Connect Timeout",
    call_timeout: "Call Timeout",
    trust_level: "Trust Level",
    connection_name: "Connection Name",
    oauth_grant: "OAuth Grant Type",
    oauth_token_url: "OAuth Token URL",
    oauth_authorization_url: "OAuth Authorization URL",
    oauth_client_id: "OAuth Client ID",
    oauth_client_secret: "OAuth Client Secret",
    oauth_scope: "OAuth Scope",
    oauth_prompt: "OAuth Prompt",
    oauth_endpoint_auth_style: "OAuth Auth Style",
  },
  api: {
    base_url: "Base URL",
    auth_mode: "Auth Mode",
    credential: "Credential",
    api_key_header: "API Key Header",
    api_key_param: "API Key Parameter",
    api_key_placement: "API Key Placement",
    username: "Username",
    password: "Password",
    connect_timeout: "Connect Timeout",
    call_timeout: "Call Timeout",
    trust_level: "Trust Level",
    max_response_bytes: "Max Response Bytes",
    catalog_id: "OpenAPI Catalog",
    connection_name: "Connection Name",
    oauth_grant: "OAuth Grant Type",
    oauth_token_url: "OAuth Token URL",
    oauth_authorization_url: "OAuth Authorization URL",
    oauth_client_id: "OAuth Client ID",
    oauth_client_secret: "OAuth Client Secret",
    oauth_scope: "OAuth Scope",
    oauth_endpoint_auth_style: "OAuth Auth Style",
    oauth_prompt: "OAuth Prompt",
    // The legacy spelling, kept so a connection the configuration file
    // declares in it still renders human labels rather than raw keys. The
    // editor never writes these.
    oauth2_token_url: "OAuth Token URL (legacy key)",
    oauth2_authorization_url: "OAuth Authorization URL (legacy key)",
    oauth2_client_id: "OAuth Client ID (legacy key)",
    oauth2_client_secret: "OAuth Client Secret (legacy key)",
    oauth2_scopes: "OAuth Scopes (legacy key)",
    oauth2_endpoint_auth_style: "OAuth Auth Style (legacy key)",
    oauth2_prompt: "OAuth Prompt (legacy key)",
    jwt_algorithm: "JWT Algorithm",
    jwt_client_secret: "JWT Client Secret",
    jwt_private_key_pem: "JWT Signing Key",
    jwt_key_id: "JWT Key ID",
    jwt_issuer: "JWT Issuer (iss)",
    jwt_subject: "JWT Subject (sub)",
    jwt_audience: "JWT Audience (aud)",
    jwt_token_lifetime: "JWT Token Lifetime",
    jwt_issued_at_skew: "JWT Issued-At Skew",
    mtls_client_cert_pem: "mTLS Client Certificate",
    mtls_client_key_pem: "mTLS Client Key",
    mtls_cert_not_after: "mTLS Cert Expiry",
    tls_ca_bundle_pem: "TLS CA Bundle",
    static_headers: "Static Headers",
  },
  graphql: {
    endpoint_url: "Endpoint URL",
    auth_mode: "Auth Mode",
    credential: "Credential",
    api_key_header: "API Key Header",
    api_key_param: "API Key Parameter",
    api_key_placement: "API Key Placement",
    username: "Username",
    password: "Password",
    connect_timeout: "Connect Timeout",
    call_timeout: "Call Timeout",
    max_response_bytes: "Max Response Bytes",
    schema_validation: "Schema Validation",
    max_query_depth: "Max Query Depth",
    namespace_depth: "Namespace Depth",
    read_only: "Read Only",
    connection_name: "Connection Name",
    description: "Description",
    oauth_grant: "OAuth Grant Type",
    oauth_token_url: "OAuth Token URL",
    oauth_authorization_url: "OAuth Authorization URL",
    oauth_client_id: "OAuth Client ID",
    oauth_client_secret: "OAuth Client Secret",
    oauth_scope: "OAuth Scope",
    oauth_endpoint_auth_style: "OAuth Auth Style",
    oauth_prompt: "OAuth Prompt",
    // The legacy spelling, kept so a connection the configuration file
    // declares in it still renders human labels rather than raw keys. The
    // editor never writes these.
    oauth2_token_url: "OAuth Token URL (legacy key)",
    oauth2_authorization_url: "OAuth Authorization URL (legacy key)",
    oauth2_client_id: "OAuth Client ID (legacy key)",
    oauth2_client_secret: "OAuth Client Secret (legacy key)",
    oauth2_scopes: "OAuth Scopes (legacy key)",
    oauth2_endpoint_auth_style: "OAuth Auth Style (legacy key)",
    oauth2_prompt: "OAuth Prompt (legacy key)",
    jwt_algorithm: "JWT Algorithm",
    jwt_client_secret: "JWT Client Secret",
    jwt_private_key_pem: "JWT Signing Key",
    jwt_key_id: "JWT Key ID",
    jwt_issuer: "JWT Issuer (iss)",
    jwt_subject: "JWT Subject (sub)",
    jwt_audience: "JWT Audience (aud)",
    jwt_token_lifetime: "JWT Token Lifetime",
    jwt_issued_at_skew: "JWT Issued-At Skew",
    mtls_client_cert_pem: "mTLS Client Certificate",
    mtls_client_key_pem: "mTLS Client Key",
    mtls_cert_not_after: "mTLS Cert Expiry",
    tls_ca_bundle_pem: "TLS CA Bundle",
    static_headers: "Static Headers",
  },
};
