//go:build integration

package knowledgebuiltin_test

// The keystone claim of #1476, against a real Postgres: a page named by the
// slug the platform ships in its own instruction text resolves, end to end,
// through the same fetch path an agent uses. Nothing below is checkable with a
// fake, because the id a built-in page carries is generated by the reconcile
// itself and differs on every deployment; the slug is the only handle shipped
// text can name.

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/txn2/mcp-data-platform/internal/platform/knowledgebuiltin"
	"github.com/txn2/mcp-data-platform/internal/platform/scriptlayer"
	"github.com/txn2/mcp-data-platform/internal/testdb"
	"github.com/txn2/mcp-data-platform/pkg/knowledge"
	"github.com/txn2/mcp-data-platform/pkg/portal/knowledgepage"
)

func TestBuiltinPages_RealDB_FetchBySlug(t *testing.T) {
	ctx := context.Background()
	store := knowledgepage.NewPostgresStore(testdb.New(t))
	require.NoError(t, knowledgebuiltin.Reconcile(ctx, store))

	searcher, ok := store.(knowledge.PageSearcher)
	require.True(t, ok, "the postgres page store no longer satisfies the provider's capability")
	provider := knowledge.NewKnowledgePagesProvider(searcher)

	// Every page the help payload names is fetchable by the slug it names.
	for _, named := range scriptlayer.KnowledgePages {
		t.Run(named.Slug, func(t *testing.T) {
			doc, owned, err := provider.Fetch(ctx, named.Reference, knowledge.Caller{})
			require.True(t, owned)
			require.NoError(t, err)
			assert.NotEmpty(t, doc.Title)
			assert.Equal(t, named.Reference, doc.Reference)

			stored, err := searcher.GetBySlug(ctx, named.Slug)
			require.NoError(t, err)
			assert.Equal(t, stored.Title, doc.Title)
			assert.Equal(t, stored.Body, doc.Body, "fetch returned something other than the page's full body")
		})
	}

	// The id form still resolves: the slug read is a fallback, never a
	// replacement.
	dashboards, err := searcher.GetBySlug(ctx, "platform-semi-dynamic-dashboards")
	require.NoError(t, err)
	byID, owned, err := provider.Fetch(ctx, knowledgepage.PageReference(dashboards.ID), knowledge.Caller{})
	require.True(t, owned)
	require.NoError(t, err)
	assert.Equal(t, dashboards.Body, byID.Body)

	// An operator who hides a built-in page hides it from fetch too: the slug
	// reports not-found, and the reconcile does not bring the page back.
	require.NoError(t, store.SoftDelete(ctx, dashboards.ID))
	_, owned, err = provider.Fetch(ctx, knowledgepage.PageReference("platform-semi-dynamic-dashboards"), knowledge.Caller{})
	assert.True(t, owned)
	assert.ErrorIs(t, err, knowledge.ErrNotFound)

	require.NoError(t, knowledgebuiltin.Reconcile(ctx, store))
	_, owned, err = provider.Fetch(ctx, knowledgepage.PageReference("platform-semi-dynamic-dashboards"), knowledge.Caller{})
	assert.True(t, owned)
	assert.ErrorIs(t, err, knowledge.ErrNotFound, "the reconcile resurrected a page an operator hid")
}
