ALTER TABLE scripts ADD COLUMN IF NOT EXISTS legacy BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE scripts ADD COLUMN IF NOT EXISTS tests_optional BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE scripts ADD COLUMN IF NOT EXISTS outputs_read_optional BOOLEAN NOT NULL DEFAULT FALSE;
