// Package task defines the benchmark task schema, loader, and the canonical
// task-set hash recorded in every run manifest.
package task

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"gopkg.in/yaml.v3"
)

// Grading kinds.
const (
	GradeNumeric = "numeric"
	GradeEntity  = "entity"
	// GradeExecSQL grades a SQL-producing task by execution-result comparison
	// (BIRD-style execution accuracy): the agent's FINAL ANSWER is a SQL query,
	// which the grader executes and compares row-for-row against the result of
	// the task's ExpectedSQL. Correctness is result-set equality, so two
	// different-but-equivalent queries both pass.
	GradeExecSQL = "exec_sql"
	// GradeState grades a mutation task by post-run state inspection (the
	// MCPMark / MCP-Universe standard, #1027): after the episode the grader
	// reads the fixture service's state dump and asserts every StateCheck
	// holds. No judge is involved.
	GradeState = "state"
	// GradeRefusal grades an irrelevance task (#1027, the BFCL
	// irrelevance-detection failure mode): the correct behavior is to state
	// that no available endpoint can do it. Pass requires the final answer
	// to declare the capability unavailable AND the episode to contain no
	// write-kind invocation; an agent that mutates state as if the request
	// were fulfillable fails deterministically.
	GradeRefusal = "refusal"
)

// Task is one benchmark task. Ground truth is generated by the dataset
// generator (bench/seedgen), never hand-typed.
type Task struct {
	// ID is unique across the task set, e.g. "s3-units-q1-total".
	ID string `yaml:"id" json:"id"`
	// Suite is the task suite, e.g. "s1" (discovery) or "s3" (knowledge traps).
	Suite string `yaml:"suite" json:"suite"`
	// Prompt is what the agent is asked.
	Prompt string `yaml:"prompt" json:"prompt"`
	// Arms lists the arm names this task applies to.
	Arms []string `yaml:"arms" json:"arms"`
	// TrapClasses tags S3 tasks with the seeded trap classes they exercise.
	TrapClasses []string `yaml:"trap_classes,omitempty" json:"trap_classes,omitempty"`
	// BudgetToolCalls caps tool calls per attempt.
	BudgetToolCalls int `yaml:"budget_tool_calls" json:"budget_tool_calls"`
	// ExpectedSQL records the reference query the generator used to compute
	// ground truth (audit trail; also drives the scripted smoke).
	ExpectedSQL string `yaml:"expected_sql,omitempty" json:"expected_sql,omitempty"`
	// GoldOperations lists the operationIds the task requires (#1027).
	// The runner computes retrieval hit rate from them: whether every
	// gold operation surfaced in some api_list_endpoints result during
	// the episode. Empty for tasks with no gold operation (irrelevance).
	GoldOperations []string `yaml:"gold_operations,omitempty" json:"gold_operations,omitempty"`
	// Grading is the deterministic grading spec.
	Grading Grading `yaml:"grading" json:"grading"`
	// Rubric lists judgment-call items recorded for manual review in the
	// pilot (LLM-judged in phase 2).
	Rubric []RubricItem `yaml:"rubric,omitempty" json:"rubric,omitempty"`
}

// Grading is a deterministic grading spec.
type Grading struct {
	// Kind is GradeNumeric or GradeEntity.
	Kind string `yaml:"kind" json:"kind"`
	// Value is the expected number (numeric only).
	Value *float64 `yaml:"value,omitempty" json:"value,omitempty"`
	// AbsTolerance is the absolute tolerance for numeric match.
	AbsTolerance float64 `yaml:"abs_tolerance,omitempty" json:"abs_tolerance,omitempty"`
	// Aliases are accepted entity identifiers (entity only), matched
	// case-insensitively as substrings of the final answer's first line.
	Aliases []string `yaml:"aliases,omitempty" json:"aliases,omitempty"`
	// WrongAliases enumerate the task's known trap answers (entity only): a
	// final answer mentioning any of them is graded incorrect even when a
	// correct alias also appears.
	WrongAliases []string `yaml:"wrong_aliases,omitempty" json:"wrong_aliases,omitempty"`
	// StateChecks are the post-run assertions (state only). All must hold.
	StateChecks []StateCheck `yaml:"state_checks,omitempty" json:"state_checks,omitempty"`
}

// StateCheck is one post-run fixture-state assertion (#1027).
type StateCheck struct {
	// Resource names the fixture state collection, e.g. "orders" or
	// "customers".
	Resource string `yaml:"resource" json:"resource"`
	// ID targets a specific row. Zero means existence mode: some row must
	// match every Fields entry (used for created rows whose id is
	// server-assigned).
	ID int64 `yaml:"id,omitempty" json:"id,omitempty"`
	// Fields maps field name to the expected post-run value. With ID set
	// they assert on that row; with ID zero they are the existence match.
	Fields map[string]any `yaml:"fields" json:"fields"`
}

// RubricItem is one judged criterion, recorded but not auto-scored in phase 1.
type RubricItem struct {
	ID   string `yaml:"id" json:"id"`
	Note string `yaml:"note" json:"note"`
}

// Validate rejects malformed tasks at load time so a broken task set fails
// before any session is spent on it.
func (t Task) Validate() error {
	switch {
	case t.ID == "":
		return errors.New("task with empty id")
	case t.Suite == "":
		return fmt.Errorf("task %s: empty suite", t.ID)
	case t.Prompt == "":
		return fmt.Errorf("task %s: empty prompt", t.ID)
	case len(t.Arms) == 0:
		return fmt.Errorf("task %s: no arms", t.ID)
	case t.BudgetToolCalls <= 0:
		return fmt.Errorf("task %s: budget_tool_calls must be positive", t.ID)
	}
	return t.validateGrading()
}

// validateGrading checks the grading spec matches its kind.
func (t Task) validateGrading() error {
	switch t.Grading.Kind {
	case GradeNumeric:
		if t.Grading.Value == nil {
			return fmt.Errorf("task %s: numeric grading requires value", t.ID)
		}
		if t.Grading.AbsTolerance < 0 {
			return fmt.Errorf("task %s: negative tolerance", t.ID)
		}
		return nil
	case GradeEntity:
		return t.validateEntityGrading()
	case GradeExecSQL:
		if t.ExpectedSQL == "" {
			return fmt.Errorf("task %s: exec_sql grading requires expected_sql", t.ID)
		}
		return nil
	case GradeState:
		return t.validateStateGrading()
	case GradeRefusal:
		if len(t.Grading.StateChecks) > 0 {
			return fmt.Errorf("task %s: refusal grading takes no state checks", t.ID)
		}
		return nil
	default:
		return fmt.Errorf("task %s: unknown grading kind %q", t.ID, t.Grading.Kind)
	}
}

// validateStateGrading checks the post-run assertions are well-formed.
func (t Task) validateStateGrading() error {
	if len(t.Grading.StateChecks) == 0 {
		return fmt.Errorf("task %s: state grading requires state_checks", t.ID)
	}
	for i, c := range t.Grading.StateChecks {
		if c.Resource == "" {
			return fmt.Errorf("task %s: state check %d has no resource", t.ID, i)
		}
		if len(c.Fields) == 0 {
			return fmt.Errorf("task %s: state check %d has no fields", t.ID, i)
		}
	}
	return nil
}

// validateEntityGrading checks alias sets. A correct alias containing a wrong
// alias would make a correct answer ungradeable (naming the truth always
// names the trap), so that combination is rejected.
func (t Task) validateEntityGrading() error {
	if len(t.Grading.Aliases) == 0 {
		return fmt.Errorf("task %s: entity grading requires aliases", t.ID)
	}
	for _, a := range t.Grading.Aliases {
		for _, w := range t.Grading.WrongAliases {
			if w != "" && strings.Contains(strings.ToLower(a), strings.ToLower(w)) {
				return fmt.Errorf("task %s: alias %q contains wrong alias %q", t.ID, a, w)
			}
		}
	}
	return nil
}

// AppliesTo reports whether the task runs under the given arm.
func (t Task) AppliesTo(arm string) bool {
	return slices.Contains(t.Arms, arm)
}

// Load reads every *.yaml task in dir (sorted by filename), validating each
// and rejecting duplicate IDs.
func Load(dir string) ([]Task, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("read task dir: %w", err)
	}
	var tasks []Task
	seen := map[string]bool{}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".yaml") {
			continue
		}
		raw, err := os.ReadFile(filepath.Join(dir, e.Name())) // #nosec G304 -- operator-supplied task dir
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", e.Name(), err)
		}
		var t Task
		if err := yaml.Unmarshal(raw, &t); err != nil {
			return nil, fmt.Errorf("parse %s: %w", e.Name(), err)
		}
		if err := t.Validate(); err != nil {
			return nil, fmt.Errorf("%s: %w", e.Name(), err)
		}
		if seen[t.ID] {
			return nil, fmt.Errorf("duplicate task id %s", t.ID)
		}
		seen[t.ID] = true
		tasks = append(tasks, t)
	}
	if len(tasks) == 0 {
		return nil, fmt.Errorf("no tasks found in %s", dir)
	}
	return tasks, nil
}

// Hash returns the canonical SHA-256 of the task set (sorted by ID, JSON
// encoded) for the run manifest.
func Hash(tasks []Task) string {
	sorted := make([]Task, len(tasks))
	copy(sorted, tasks)
	slices.SortFunc(sorted, func(a, b Task) int { return strings.Compare(a.ID, b.ID) })
	raw, err := json.Marshal(sorted)
	if err != nil {
		// Task is a plain data struct; marshal cannot fail on validated input.
		panic(fmt.Sprintf("marshal task set: %v", err))
	}
	sum := sha256.Sum256(raw)
	return hex.EncodeToString(sum[:])
}
