-- E2E Test Database Initialization
--
-- Intentionally minimal. The platform owns its schema through the embedded
-- golang-migrate migrations it runs at startup (oauth, audit, knowledge,
-- memory, resources, the `vector` extension, etc.). This file previously
-- pre-created simplified OAuth/audit tables, which then conflicted with those
-- migrations ("column ... does not exist") and prevented the assembled platform
-- from starting against the e2e database — defeating the gate. Let migrations
-- be the single source of truth; this file only needs to leave a clean database
-- (created by the compose POSTGRES_DB env) for them to populate.
SELECT 1;
