// Command seedgen regenerates the benchmark's committed seed artifacts and
// task set from the fixed-seed dataset model (bench/internal/gen). Ground
// truth is computed from the generated rows at generation time, never
// hand-typed; a determinism test diffs a fresh regeneration against the
// committed files.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"

	"github.com/txn2/mcp-data-platform/bench/internal/curriculum"
	"github.com/txn2/mcp-data-platform/bench/internal/gen"
	"github.com/txn2/mcp-data-platform/bench/internal/protocol"
	"github.com/txn2/mcp-data-platform/bench/internal/task"
)

func main() {
	seedDir := flag.String("seed-dir", "seed", "output directory for seed artifacts")
	tasksDir := flag.String("tasks-dir", "tasks", "output directory for task YAML and the smoke script")
	protocolsDir := flag.String("protocols-dir", "protocols", "output directory for S5 lifecycle protocol YAML and smoke")
	curriculumDir := flag.String("curriculum-dir", "curriculum", "output directory for the cold-start curriculum YAML")
	flag.Parse()
	if err := run(*seedDir, *tasksDir, *protocolsDir, *curriculumDir); err != nil {
		fmt.Fprintln(os.Stderr, "seedgen:", err)
		os.Exit(1)
	}
}

// run generates the dataset and writes every artifact.
func run(seedDir, tasksDir, protocolsDir, curriculumDir string) error {
	ds := gen.Generate()
	if err := writeSeedArtifacts(ds, seedDir); err != nil {
		return err
	}
	tasks := ds.Tasks()
	if err := writeTasks(tasks, tasksDir); err != nil {
		return err
	}
	if err := writeSmokeScript(tasks, tasksDir); err != nil {
		return err
	}
	protocols := ds.Protocols()
	if err := writeProtocols(protocols, protocolsDir); err != nil {
		return err
	}
	if err := writeLifecycleSmoke(protocols, protocolsDir); err != nil {
		return err
	}
	cur := ds.Curriculum()
	if err := writeCurriculum(cur, curriculumDir); err != nil {
		return err
	}
	if err := writeColdStartSmoke(cur, tasks, curriculumDir); err != nil {
		return err
	}
	fmt.Printf("seedgen: %d customers, %d orders, %d tasks (hash %s), %d protocols (hash %s), curriculum %s (%d lessons, hash %s)\n",
		len(ds.Customers), len(ds.Orders), len(tasks), task.Hash(tasks), len(protocols), protocol.Hash(protocols),
		cur.ID, len(cur.Lessons), curriculum.Hash([]curriculum.Curriculum{cur}))
	return nil
}

// writeSeedArtifacts emits the Trino SQL, DataHub MCEs, and knowledge-page SQL.
func writeSeedArtifacts(ds *gen.Dataset, dir string) error {
	mces, err := ds.DataHubMCEs()
	if err != nil {
		return fmt.Errorf("render datahub mces: %w", err)
	}
	emptyMCEs, err := ds.DataHubMCEsEmpty()
	if err != nil {
		return fmt.Errorf("render empty datahub mces: %w", err)
	}
	files := map[string][]byte{
		filepath.Join(dir, "trino", "setup.sql"):               []byte(ds.TrinoSQL()),
		filepath.Join(dir, "datahub", "bench_mces.json"):       mces,
		filepath.Join(dir, "datahub", "bench_mces_empty.json"): emptyMCEs,
		filepath.Join(dir, "postgres", "knowledge_pages.sql"):  []byte(ds.KnowledgePagesSQL()),
	}
	for path, content := range files {
		if err := writeFile(path, content); err != nil {
			return err
		}
	}
	return nil
}

// writeTasks emits one YAML file per task.
func writeTasks(tasks []task.Task, dir string) error {
	for _, t := range tasks {
		raw, err := yaml.Marshal(t)
		if err != nil {
			return fmt.Errorf("marshal task %s: %w", t.ID, err)
		}
		header := "# Generated by bench/seedgen; ground truth is computed from the seeded dataset.\n# Do not edit; regenerate with `make bench-gen`.\n"
		if err := writeFile(filepath.Join(dir, t.ID+".yaml"), append([]byte(header), raw...)); err != nil {
			return err
		}
	}
	return nil
}

// writeSmokeScript emits the deterministic playback script for the scripted
// adapter.
func writeSmokeScript(tasks []task.Task, dir string) error {
	raw, err := json.MarshalIndent(gen.ScriptedSmoke(tasks), "", "  ")
	if err != nil {
		return fmt.Errorf("marshal smoke script: %w", err)
	}
	return writeFile(filepath.Join(dir, "scripted-smoke.json"), append(raw, '\n'))
}

// writeProtocols emits one YAML file per S5 lifecycle protocol.
func writeProtocols(protocols []protocol.Protocol, dir string) error {
	for _, p := range protocols {
		if err := p.Validate(); err != nil {
			return fmt.Errorf("generated protocol %s invalid: %w", p.ID, err)
		}
		raw, err := yaml.Marshal(p)
		if err != nil {
			return fmt.Errorf("marshal protocol %s: %w", p.ID, err)
		}
		header := "# Generated by bench/seedgen; recall/update answers are computed from the seeded dataset.\n# Do not edit; regenerate with `make bench-gen`.\n"
		if err := writeFile(filepath.Join(dir, p.ID+".yaml"), append([]byte(header), raw...)); err != nil {
			return err
		}
	}
	return nil
}

// writeCurriculum emits the cold-start curriculum as a single YAML document.
func writeCurriculum(cur curriculum.Curriculum, dir string) error {
	if err := cur.Validate(); err != nil {
		return fmt.Errorf("generated curriculum %s invalid: %w", cur.ID, err)
	}
	raw, err := yaml.Marshal(cur)
	if err != nil {
		return fmt.Errorf("marshal curriculum %s: %w", cur.ID, err)
	}
	header := "# Generated by bench/seedgen; the eval ground truth is the committed S3 task suite.\n# Do not edit; regenerate with `make bench-gen`.\n"
	return writeFile(filepath.Join(dir, cur.ID+".yaml"), append([]byte(header), raw...))
}

// writeColdStartSmoke emits the deterministic per-episode playback for the
// no-API-key cold-start smoke, over the curriculum lessons and the eval suite.
func writeColdStartSmoke(cur curriculum.Curriculum, tasks []task.Task, dir string) error {
	var evalTasks []task.Task
	for _, t := range tasks {
		if t.Suite == cur.EvalSuite {
			evalTasks = append(evalTasks, t)
		}
	}
	raw, err := json.MarshalIndent(gen.ScriptedColdStartSmoke(cur, evalTasks), "", "  ")
	if err != nil {
		return fmt.Errorf("marshal cold-start smoke: %w", err)
	}
	return writeFile(filepath.Join(dir, "scripted-cold-start-smoke.json"), append(raw, '\n'))
}

// writeLifecycleSmoke emits the deterministic per-episode playback for the
// no-API-key lifecycle smoke.
func writeLifecycleSmoke(protocols []protocol.Protocol, dir string) error {
	raw, err := json.MarshalIndent(gen.ScriptedLifecycleSmoke(protocols), "", "  ")
	if err != nil {
		return fmt.Errorf("marshal lifecycle smoke: %w", err)
	}
	return writeFile(filepath.Join(dir, "scripted-lifecycle-smoke.json"), append(raw, '\n'))
}

// writeFile writes content creating parent directories. Artifacts are
// world-readable (0644): they are committed repository sources (a git checkout
// materializes them 0644 regardless), and the Trino seed file is copied into a
// container whose CLI runs as a non-root user that must read it.
func writeFile(path string, content []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil { // #nosec G301 -- committed source tree
		return fmt.Errorf("mkdir for %s: %w", path, err)
	}
	if err := os.WriteFile(path, content, 0o644); err != nil { // #nosec G306 -- committed, non-secret artifacts
		return fmt.Errorf("write %s: %w", path, err)
	}
	// WriteFile's mode applies only on creation; force it for pre-existing
	// files so regeneration also repairs a wrong mode.
	if err := os.Chmod(path, 0o644); err != nil { // #nosec G302 -- committed, non-secret artifacts
		return fmt.Errorf("chmod %s: %w", path, err)
	}
	return nil
}
