// Command seedgen regenerates the benchmark's committed seed artifacts and
// task set from the fixed-seed dataset model (bench/internal/gen). Ground
// truth is computed from the generated rows at generation time, never
// hand-typed; a determinism test diffs a fresh regeneration against the
// committed files.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"

	"github.com/txn2/mcp-data-platform/bench/internal/gen"
	"github.com/txn2/mcp-data-platform/bench/internal/task"
)

func main() {
	seedDir := flag.String("seed-dir", "seed", "output directory for seed artifacts")
	tasksDir := flag.String("tasks-dir", "tasks", "output directory for task YAML and the smoke script")
	flag.Parse()
	if err := run(*seedDir, *tasksDir); err != nil {
		fmt.Fprintln(os.Stderr, "seedgen:", err)
		os.Exit(1)
	}
}

// run generates the dataset and writes every artifact.
func run(seedDir, tasksDir string) error {
	ds := gen.Generate()
	if err := writeSeedArtifacts(ds, seedDir); err != nil {
		return err
	}
	tasks := ds.Tasks()
	if err := writeTasks(tasks, tasksDir); err != nil {
		return err
	}
	if err := writeSmokeScript(tasks, tasksDir); err != nil {
		return err
	}
	fmt.Printf("seedgen: %d customers, %d orders, %d tasks, task-set hash %s\n",
		len(ds.Customers), len(ds.Orders), len(tasks), task.Hash(tasks))
	return nil
}

// writeSeedArtifacts emits the Trino SQL, DataHub MCEs, and knowledge-page SQL.
func writeSeedArtifacts(ds *gen.Dataset, dir string) error {
	mces, err := ds.DataHubMCEs()
	if err != nil {
		return fmt.Errorf("render datahub mces: %w", err)
	}
	files := map[string][]byte{
		filepath.Join(dir, "trino", "setup.sql"):              []byte(ds.TrinoSQL()),
		filepath.Join(dir, "datahub", "bench_mces.json"):      mces,
		filepath.Join(dir, "postgres", "knowledge_pages.sql"): []byte(ds.KnowledgePagesSQL()),
	}
	for path, content := range files {
		if err := writeFile(path, content); err != nil {
			return err
		}
	}
	return nil
}

// writeTasks emits one YAML file per task.
func writeTasks(tasks []task.Task, dir string) error {
	for _, t := range tasks {
		raw, err := yaml.Marshal(t)
		if err != nil {
			return fmt.Errorf("marshal task %s: %w", t.ID, err)
		}
		header := "# Generated by bench/seedgen; ground truth is computed from the seeded dataset.\n# Do not edit; regenerate with `make bench-gen`.\n"
		if err := writeFile(filepath.Join(dir, t.ID+".yaml"), append([]byte(header), raw...)); err != nil {
			return err
		}
	}
	return nil
}

// writeSmokeScript emits the deterministic playback script for the scripted
// adapter.
func writeSmokeScript(tasks []task.Task, dir string) error {
	raw, err := json.MarshalIndent(gen.ScriptedSmoke(tasks), "", "  ")
	if err != nil {
		return fmt.Errorf("marshal smoke script: %w", err)
	}
	return writeFile(filepath.Join(dir, "scripted-smoke.json"), append(raw, '\n'))
}

// writeFile writes content creating parent directories. Artifacts are
// world-readable (0644): they are committed repository sources (a git checkout
// materializes them 0644 regardless), and the Trino seed file is copied into a
// container whose CLI runs as a non-root user that must read it.
func writeFile(path string, content []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil { // #nosec G301 -- committed source tree
		return fmt.Errorf("mkdir for %s: %w", path, err)
	}
	if err := os.WriteFile(path, content, 0o644); err != nil { // #nosec G306 -- committed, non-secret artifacts
		return fmt.Errorf("write %s: %w", path, err)
	}
	// WriteFile's mode applies only on creation; force it for pre-existing
	// files so regeneration also repairs a wrong mode.
	if err := os.Chmod(path, 0o644); err != nil { // #nosec G302 -- committed, non-secret artifacts
		return fmt.Errorf("chmod %s: %w", path, err)
	}
	return nil
}
